site_name: OSG Operations
site_url: https://www.opensciencegrid.org/operations/
repo_url: https://github.com/opensciencegrid/operations/
google_analytics: ['UA-69012-29', 'opensciencegrid.github.io']
theme: 
  name: material
  custom_dir: osgthedocs
  favicon: 'img/favicon.ico'  

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Services:
  - Installing GlideinWMS Factory: 'services/install-gwms-factory.md'
  - Topology Service: 'services/topology.md'
  - Topology and Contacts Data: 'services/topology-contacts-data.md'
  - Sending Announcements: 'services/sending-announcements.md'
- Service Level Agreements:
  - 'HTCondor Collector': 'SLA/collector.md'
  - 'MyOSG': 'SLA/myosg.md'
  - OASIS Stratum-0: 'SLA/oasis.md'
  - OASIS Replica: 'SLA/oasis-replica.md'
  - 'OIM': 'SLA/oim.md'
  - 'XDLogin': 'SLA/xdlogin.md'
- External OASIS repositories: 'external-oasis-repos.md'

markdown_extensions:
  - admonition
  - codehilite
#  - toc(permalink=true)
  - toc
  - osg_markdown.colors

